Adjust the deploymet job for ECR images
cfpb/marathon-cli pull request #10
Opened 2022-04-21 20:02 UTC by higs4281

As part of this refactor, required by a change in Docker registries,
we drop the json-as-env-var structure, which was brittle, and
build the json configuration in the python script.

cc @dvbalen

2022-04-21 21:06 UTC, KatherynRizek approved these changes
I'm not the most familiar with this process but nothing seems glaringly wrong. If there are particular testing steps I should take, please let me know!

2022-04-21 21:32 UTC, higs4281 commented
@KatherynRizek Thanks for the eyes. I hope to spread awareness of the code that deploys our app.

2022-04-22 06:35 UTC, higs4281 commented
For posterity: This change won't have immediate effect on most active jobs because most point at various branches of a personal fork of this repo created by a departed staffer: https://github.com/tanderegg/marathon-cli

As we update jobs, we can point them at this repo to use a centralized json form for apps.

2022-05-10 00:55 UTC, imuchnik requested changes

2022-05-10 13:07 UTC, higs4281 commented on marathon-cli.py
> +            "ES_HOST": "https://es2.data.cfpb.local/",
good catch. Now passed from Jenkins.

2022-05-12 18:14 UTC, imuchnik approved these changes

2022-05-12 18:14 UTC, merged